### PR TITLE
This closes #5 implementing retry policy.

### LINKED ISSUE #5: Add Retry Kommand capability.
Just as we can cancel a Kommand, we want add the capability to retry them after failure.

We have to think about how it would work, a good starting point could be our [NetClient retry policy](https://github.com/intelygenz/NetClient-iOS/blob/develop/URLSession/NetURLSession.swift#L157).

### PR DESCRIPTION
**Pull request by alexruperez**
### Issue Link 🔗
https://github.com/intelygenz/Kommander-iOS/issues/5

### Goals ⚽
Close https://github.com/intelygenz/Kommander-iOS/issues/5 implementing retry policy.

### Implementation Details 🚧
Retry closure with error and execution count params called on executor when the Kommand fails.

Note: You can "suspend" (for example sleep) the retry closure to implement timed retries, because it's executed using the executor.

---
This change is [Reviewable](https://reviewable.io/reviews/intelygenz/kommander-ios/14)

### CODE REVIEW

**Comment by danicoello** [comment]
Maybe a number of retries policy could be interesting but I think that we must not implement timed retries. This functionality should be delegated to the code that uses Kommander instead Kommander itself.

Being strict on definition, a retry functionality is out of scope of an async execution library and this policy should be implemented in the caller code instead in the library because is not a general purpose feature to be used in the majority of programs like a cancel feature, for example.

**Review by IGZJoseAngelCuadrado — APPROVED** [review]

**Comment by juantrias** [comment]
I agree with Dani, implementing timed retries is beyond the scope and adds unnecessary complexity: retry closure should be called on the deliverer queue (tipically the main thread). Calling the retry closure on the executor queue and calling sleep() inside the retry closure is a bit dirty and is confusing for the user of the API, that expects to write synchronous code inside this closure

---

Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[Source/Kommand.swift, line 121 at r1](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L33yk-niuGgBFjnV7rb:-L33yk-niuGgBFjnV7rc:b6f3f35) ([raw file](https://github.com/intelygenz/kommander-ios/blob/b59e0763b95dfbcf14211f5bc83692c2290fbb46/Source/Kommand.swift#L121)):*
> ```Swift
>                     }
>                 }
>             } catch {
> ```

I think you need to increment `executionCount` in case of error. You need to add some unit tests :wink:

---

*[Source/Kommand.swift, line 127 at r1](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L33zuL-uP49jmrvGyQs:-L33zuL-uP49jmrvGyQt:bsa14rx) ([raw file](https://github.com/intelygenz/kommander-ios/blob/b59e0763b95dfbcf14211f5bc83692c2290fbb46/Source/Kommand.swift#L127)):*
> ```Swift
>                 self.deliverer?.execute {
>                     self.state = .finished
>                     self.errorClosure?(error)
> ```

I would not call `errorClosure` in case of retry. As a regular callback it should be called only once. I think most of the times we will only handle the error and display it on the UI when we have reached the maximum number of retries and we may require user intervention. Now in the `errorClosure` we don't know if we are going to retry or not

---

*[Source/Kommand.swift, line 128 at r1](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L340ZJGXYviKZmItalb:-L340ZJGXYviKZmItalc:b-zg213) ([raw file](https://github.com/intelygenz/kommander-ios/blob/b59e0763b95dfbcf14211f5bc83692c2290fbb46/Source/Kommand.swift#L128)):*
> ```Swift
>                     self.state = .finished
>                     self.errorClosure?(error)
>                     self.executor?.execute {
> ```

I would not execute the `retryClosure` in a background thread. I think that all closures that are tipically defined in the Controller (success and error callbacks and retry) should be executed in the main thread to keep all the Controller code safe in the main thread. I think that the timed retries use case should not be supported, it is very specific.

---

*[Source/Kommander.swift, line 128 at r1](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L33zMKzC3IOrhZYnwi0:-L33zMKzC3IOrhZYnwi1:b6f3f35) ([raw file](https://github.com/intelygenz/kommander-ios/blob/b59e0763b95dfbcf14211f5bc83692c2290fbb46/Source/Kommander.swift#L128)):*
> ```Swift
>                     }
>                 }
>             } catch {
> ```

I think you need to increment `executionCount` in case of error. You need to add some unit tests :wink:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-:-L3444R6t4_nijaNgMli:b-wze3or)*

**Review by juantrias — CHANGES_REQUESTED** [review]
See Comments from Reviewable

**Comment by alexruperez** [comment]
@juantrias test added, ready for re-review. 😃

**Comment by juantrias** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 3 of 31 files at r3.
Review status: 6 of 32 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Source/Kommand.swift, line 121 at r1](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L33yk-niuGgBFjnV7rb:-L3CtRaldRUEdX2Skv46:b32w0x) ([raw file](https://github.com/intelygenz/kommander-ios/blob/b59e0763b95dfbcf14211f5bc83692c2290fbb46/Source/Kommand.swift#L121)):*
<details><summary><i>Previously, juantrias (Juan Trías) wrote…</i></summary><blockquote>

I think you need to increment `executionCount` in case of error. You need to add some unit tests :wink:
</blockquote></details>

OK

---

*[Source/Kommand.swift, line 127 at r1](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L33zuL-uP49jmrvGyQs:-L3Cs6Fwt1u4d7c0o9Xo:b32w0x) ([raw file](https://github.com/intelygenz/kommander-ios/blob/b59e0763b95dfbcf14211f5bc83692c2290fbb46/Source/Kommand.swift#L127)):*
<details><summary><i>Previously, juantrias (Juan Trías) wrote…</i></summary><blockquote>

I would not call `errorClosure` in case of retry. As a regular callback it should be called only once. I think most of the times we will only handle the error and display it on the UI when we have reached the maximum number of retries and we may require user intervention. Now in the `errorClosure` we don't know if we are going to retry or not
</blockquote></details>

OK

---

*[Source/Kommand.swift, line 128 at r1](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L340ZJGXYviKZmItalb:-L3Csou2JrGni1UMS_k7:b32w0x) ([raw file](https://github.com/intelygenz/kommander-ios/blob/b59e0763b95dfbcf14211f5bc83692c2290fbb46/Source/Kommand.swift#L128)):*
<details><summary><i>Previously, juantrias (Juan Trías) wrote…</i></summary><blockquote>

I would not execute the `retryClosure` in a background thread. I think that all closures that are tipically defined in the Controller (success and error callbacks and retry) should be executed in the main thread to keep all the Controller code safe in the main thread. I think that the timed retries use case should not be supported, it is very specific.
</blockquote></details>

OK

---

*[Source/Kommand.swift, line 189 at r3](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L3CufEpc8336ZNWjOz2:-L3CufEpc8336ZNWjOz3:b-bwh3n0) ([raw file](https://github.com/intelygenz/kommander-ios/blob/2b599ce6f28ff8a43988044d8e8e4475c6faace7/Source/Kommand.swift#L189)):*
> ```Swift
>     /// Cancel Kommand<Result>
>     @discardableResult open func cancel(_ throwingError: Bool = false) -> Self {
>         guard state == .running else {
> ```

I think we should be able to cancel a `Kommand` in state `.ready`

---

*[Source/Kommander.swift, line 128 at r1](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L33zMKzC3IOrhZYnwi0:-L3Cvd7K7pBbp9UtxZ7A:b32w0x) ([raw file](https://github.com/intelygenz/kommander-ios/blob/b59e0763b95dfbcf14211f5bc83692c2290fbb46/Source/Kommander.swift#L128)):*
<details><summary><i>Previously, juantrias (Juan Trías) wrote…</i></summary><blockquote>

I think you need to increment `executionCount` in case of error. You need to add some unit tests :wink:
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-:-L3Cxn7skX3PpxEXtj6K:bnfp4nl)*

**Comment by juantrias** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: 6 of 32 files reviewed at latest revision, 5 unresolved discussions.

---

*[Source/Kommand.swift, line 189 at r3](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-L3CufEpc8336ZNWjOz2:-L3DBLnlT-vw5gStu8zE:b32w0x) ([raw file](https://github.com/intelygenz/kommander-ios/blob/2b599ce6f28ff8a43988044d8e8e4475c6faace7/Source/Kommand.swift#L189)):*
<details><summary><i>Previously, juantrias (Juan Trías) wrote…</i></summary><blockquote>

I think we should be able to cancel a `Kommand` in state `.ready`
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/intelygenz/kommander-ios/14#-:-L3DBjHptqFpsX_qJuZ1:bnfp4nl)*

**Review by juantrias — APPROVED** [review]

**Pull request merged**
